package com.loancash.loancash.controller;

import java.text.DateFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

import com.google.gson.Gson;
import com.loancash.loancash.entity.CreditHistory;
import com.loancash.loancash.model.CompleteLoan;
import com.loancash.loancash.model.TransferModel;
import com.loancash.loancash.repo.CreditHistoryRepo;

import utility.SendSms;

@RestController
public class CompletePayment {
	
	@Autowired
	private CreditHistoryRepo credithistoryrepo;

	@PostMapping("/completepayment")
	public String completepayment(@RequestBody String strcompleteloan) {
	
		Gson gson = new Gson();
	
		CompleteLoan completeloan = gson.fromJson(strcompleteloan /*responseBody.string()*/, CompleteLoan.class);
	 
		SendSms sendsms = new SendSms();
		
		String status = completeloan.getCompleteloandata().getStatus();
		String transfercode = completeloan.getCompleteloandata().getTransfer_code();
		String bankname = completeloan.getCompleteloandata().getRecipient().getDetails().getBank_name();
	
		String account_number = completeloan.getCompleteloandata().getRecipient().getDetails().getAccount_number();
		
		////////////////////add star to the account number
		String formted_account_number = account_number.substring(0, 3)+"****"+account_number.substring(7);
					
		
		/////////////////////////////////////////////////////////////////////get the credit history object
		CreditHistory credithistory = credithistoryrepo.findBytranfercodeandstatus(transfercode, "pending");
		
		////////////////add format the amount as currency
		NumberFormat  nf = NumberFormat.getInstance(new Locale("en","US"));
		String foramted_amount = nf.format(Double.parseDouble(credithistory.getAmount()));
		
		if(credithistory != null) 
		{
			///////////////////////////////////////////////////////////////////////////format the amount to pay
			String amounttopay = nf.format(Double.parseDouble(credithistory.getAmountToPay()));
			
			System.out.print("");
			
			//////////////////////////////////////////////////////////////////////////////format the date to pay
			DateFormat df = new SimpleDateFormat("E, MMM dd yyyy HH:mm:ss");
			String format_date = df.format(new Date(Long.parseLong(credithistory.getDueDate()))); 
			
			String phonenumber = credithistory.getPhonenumber().getPhonenumber();
			
			System.out.print("status is: "+status);
			
			if(status.equalsIgnoreCase("success"))
			{
				credithistory.setBorrowStatus("oweing");
				
				//////////update the database
				credithistoryrepo.save(credithistory);
				
				///////////////////////send message to the person
				String message = "Hurray! Your Aguila "
						+ " loan of N"+foramted_amount+" is now in your "+formted_account_number
						+ " account at "+bankname+" Bank. Remember the total of N"+amounttopay
						+ " must be paid by"+ format_date+" to continue borrowing.";
				//sendsms.sendCode(phonenumber, "Your Account has been credited");
				
				System.out.print(message);
				
			}else if(status.equalsIgnoreCase("failed")){
				
				String message = "Hello! Your Aguila "
						+ " loan of N"+foramted_amount+" could not be transfered due to bank issues please try again.";
				
				System.out.print(message);
			}
		
		}else {
			
			////////////////this shoud snd message to the admin bc it was generated by the system
			System.out.print("error from the system");
		}
		
		return "ok";
	}
}
